name: ReThinc
favicon: null
layout_spectrum: 0.836748585337773
typography_spectrum: 0.9105895301327109
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.32552123279310763
  lightness: 0.4031377313658595
  saturation: 0.6169519179966301
  rhythmicContrast: 0.5184150871355087
purpose: []
