name: ReThinc
favicon: null
layout_spectrum: 1
typography_spectrum: 0.2621
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#b4d6f1'
    - '#848484'
    - '#d4d4d4'
    - '#b2b2b2'
  brandStrength: 0.25
  lightness: 0.4031377313658595
  saturation: 0.6169519179966301
  rhythmicContrast: 0.5184150871355087
purpose: []
